import type { Metadata } from "next";
import { Geist, Geist_Mono, Baloo_2,Poppins  } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AuthProvider } from "../context/Authcontext"; // ✅ Import your context provider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const baloo = Baloo_2({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"], // available weights
  variable: "--font-baloo", // custom CSS variable
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: [
    "100", "200", "300", "400", "500",
    "600", "700", "800", "900"
  ],
  variable: "--font-poppins",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kiddymaitri",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${baloo.variable} ${poppins.variable}`}
      >
        <AuthProvider>
          {" "}
          {/* ✅ Wrap your entire app */}
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}